spring.application.name=receitas

# spring.datasource.url=jdbc:mysql://localhost:3306/bd_receitas?serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/bd_receitas
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true